# Generated by Django 3.0.1 on 2019-12-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharImprovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=3)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=32)),
                ('char_improvements', models.ManyToManyField(to='race.CharImprovements')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=32)),
                ('size', models.CharField(max_length=20)),
                ('speed', models.IntegerField()),
                ('char_improvements', models.ManyToManyField(to='race.CharImprovements')),
                ('sub_races', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='race.SubRace')),
            ],
        ),
    ]
