# Generated by Django 3.0.1 on 2019-12-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_race_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrace',
            name='name',
            field=models.CharField(default='default', max_length=32),
        ),
        migrations.AlterField(
            model_name='race',
            name='sub_races',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='race.SubRace'),
        ),
    ]
